homepage/homepage/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('news.urls'),),
    path('member/',include('member.urls'),),
    path('research/',include('research.urls'),),
    path('lab/',include('lab.urls'),),
    path('news/',include('news.urls'),),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

homepage/lab/urls.py
from django.urls import path,include
from . import views

app_name = 'lab'

urlpatterns = [
    path('',views.IndexView.as_view(),name="index"),
]

homepage/member/urls.py
from django.urls import path,include
from . import views

app_name = 'member'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
]

homepage/news/urls.py
from django.urls import path,include
from . import views

app_name = 'news'

urlpatterns = [
    path('',views.TemplateView.as_view(),name="top"),
    path("news/",views.IndexView.as_view(),name="index"),
    path("news/category/<int:pk>/",views.CategoryView.as_view(),name="category"),
    path("news/detail/<int:pk>/",views.DetailView.as_view(),name="detail"),
    # path()
]

homepage/research/urls.py
from django.urls import path,include
from . import views

app_name = 'research'

urlpatterns = [
    path('',views.IndexView.as_view(),name="index"),
]

homepage/lab/models.py
from django.db import models

# Create your models here.

class Lab(models.Model):
    title = models.CharField("タイトル",max_length=30)
    text = models.TextField("内容")

    def __str__(self):
        return self.title

homepage/member/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

POSITION_CHOICES = (
("0","教授"),
("1","准教授"),
("2","助教授"),
("3","技術職員"),
("4","PD"),
("5","D3"),
("6","D2"),
("7","D1"),
("8","M2"),
("9","M1"),
("10","B4"),
)

list_year = ["01","02","03"]
year = str(timezone.now()).split("-")[0]
month = str(timezone.now()).split("-")[1]

class Member(models.Model):

    def current_year(year,month):
        if month == month in list_year:
            year = str(int(year) - 1)
            return year

    name = models.CharField("氏名",max_length=20)
    publish_name = models.CharField("公開する名前",max_length=20)
    birthplace = models.CharField("出身地",max_length=20,blank=True)
    position = models.CharField("身分",blank=False,max_length=3,choices=POSITION_CHOICES,default="")
    current_year = models.CharField("現在の年度",blank=False,max_length=4,default=year)
    assigned_year = models.CharField("配属された年度",blank=False,max_length=4,default="")
    progress = models.CharField("進路",blank=True,max_length=50,default="宮崎大学工学部→")
    hobby = models.CharField("趣味",blank=True,max_length=100,default="")
    created_at = models.DateTimeField('作成日',default=timezone.now)

    def __str__(self):
        return (self.name)

homepage/news/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    '''カテゴリ'''

    name = models.CharField('カテゴリ名',max_length=255)
    created_at = models.DateTimeField('作成日',default=timezone.now)

    def __str__(self):
        return self.name

class Post(models.Model):
    '''ニュースの記事'''

    title = models.CharField('タイトル',max_length=255)
    text = models.TextField('本文')
    image = models.ImageField('写真',upload_to='media/',blank=True,default="media/no_image.jpg")
    category = models.ForeignKey(Category,verbose_name='カテゴリ',on_delete=models.PROTECT)
    created_at = models.DateTimeField('作成日',max_length=20,default=timezone.now)

    def __str__(self):
        return self.title


class Blog(models.Model):
    """記事"""
    title = models.CharField('タイトル', max_length=255)
    text = models.TextField('本文')
    category = models.ForeignKey(
        Category, verbose_name='カテゴリ', on_delete=models.PROTECT)
    thumnail = models.ImageField(
        'サムネイル', upload_to='post_thumbnail/%Y/%m/%d/', blank=True, null=True)
    is_publick = models.BooleanField('公開可能か?', default=True)
    friend_posts = models.ManyToManyField(
        'self', verbose_name='関連記事', blank=True)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.title

class Image(models.Model):
    """記事に紐づく画像ファイル"""
    title = models.CharField('タイトル', max_length=255, blank=True)
    post = models.ForeignKey(
    Blog, verbose_name='記事', on_delete=models.PROTECT,
    )
    src = models.ImageField('画像', upload_to='images/%Y/%m/%d/', help_text='送信後、一度保存してください。')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return '間接リンク:[filter imgpk]{0}[end] 直接リンク:[filter img]{1}[end]'.format(self.pk, self.src.url)

homepage/research/models.py
from django.db import models

# Create your models here.

class Research(models.Model):
    title = models.CharField("タイトル",max_length=30)
    text = models.TextField("内容")

    def __str__(self):
        return self.title

homepage/lab/views.py
from django.shortcuts import render
from .models import Lab
from django.views import generic
from member.models import Member

# Create your views here.


class IndexView(generic.ListView):
    model = Lab

    def get_context_data(self,**kwargs):
        list_assigned_year =  [str(num) for num in range(2016,2100,1)]
        context = super().get_context_data(**kwargs)
        for x in list_assigned_year:
            # print (num)
            context["qs_" + x] = Member.objects.filter(assigned_year=x)
        # context["qs_2016"] = Member.objects.filter(assigned_year="2016")
        return context

homepage/member/views.py
from django.shortcuts import render
from .models import Member
from django.views import generic
from django.utils import timezone

list_number =  [str(num) for num in range(0,11,1)]
year = str(timezone.now()).split("-")[0]

# Create your views here.
class IndexView(generic.ListView):
    model = Member

    def current_year(year,month):
        if month == month in list_year:
            year = str(int(year) - 1)
            return year

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        for num in list_number:
            context["qs" + num + "s"] = Member.objects.filter(position=num,current_year=year)
        return context

homepage/news/views.py
from django.shortcuts import render,get_object_or_404
from django.views import generic
from .models import Post,Category
from django.db.models import Q

class TemplateView(generic.ListView):
    model = Post
    template_name = 'news/top.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # はじめに継承元のメソッドを呼び出す
        context["post_list"] = Post.objects.order_by('-created_at')[:3]
        return context

# Create your views here.
class IndexView(generic.ListView):
    model = Post
    paginate_by = 5

    def get_queryset(self):
        queryset = Post.objects.order_by('-created_at')
        keyword = self.request.GET.get('keyword')
        if keyword:
            queryset = queryset.filter(
            Q(title__icontains=keyword) | Q(text__icontains=keyword)
            )
        return queryset


class CategoryView(generic.ListView):
    models = Post
    paginate_by = 5

    def get_queryset(self):
        category = get_object_or_404(Category,pk=self.kwargs['pk'])
        queryset = Post.objects.order_by('-created_at').filter(category=category)

        return queryset

class DetailView(generic.DetailView):
    model = Post

homepage/research/views.py
from django.shortcuts import render
from .models import Research
from django.views import generic

# Create your views here.

class IndexView(generic.ListView):
    model = Research

homepage/lab/templates/lab/lab_list.html
{% extends 'news/base.html' %}

{% block content %}

{% for lab in lab_list %}
<h3>{{ lab.title }}</h3>
<p>{{ lab.text | linebreaksbr | urlize }}</p>
<hr>
{% endfor %}

<h3>進路</h3>
<h6>2017年配属</h6>
{% for qs in qs_2017 %}
<p>{{qs.progress}}</p>
{% endfor %}

<h6>2016年配属</h6>
{% for qs in qs_2016 %}
<p>{{qs.progress}}</p>
{% endfor %}

{% endblock %}

homepage/member/templates/member/base.html
<!doctype html>
<html lang="ja">
  <head>
    <title>森研究室</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% block extracss %}{% endblock %}

    <!-- <title>{% block title%}{% endblock %}</title> -->
  </head>
  <body>
    <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <!-- <a class="navbar-brand" href="#">news</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button> -->

      <div class="navbar-collapse collapse show" id="navbarSupportedContent" style="">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'news:index' %}">Home</a>
          <li>
          <li class="nav-item">
            <a class="nav-link" href="# ">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'news:index' %}">News</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'research:index' %}">Research</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Member</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About Lab</a>
          </li>
          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'news:index' %}">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="keyword">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="jumbotron">
      <h1 class="display-3">wellcom,mlab!</h1>
        <p class="lead">次世代のX線天文衛星に搭載するのX線検出器開発や天体解析をしています。</p>
          <hr class="my-2">
      <!-- <p>It uses utility classes for typography and
         spacing to space content out within the larger container.</p> -->
      <!-- <p class="lead"> -->
        <!-- <a class="btn btn-primary btn-lg" href="#!" role="button">someaction</a> -->
        </p>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}
          {% endblock %}
        </div>
        <div class="col-md-4">
          <ul class="list-group">
            <h4 class="text-center">目次 | Contents</h4>
            <li class="list-group-item"><a href="{% url 'news:index' %}">ホーム   | Home</a></li>
            <li class="list-group-item"><a href="{% url 'news:index' %}">ニュース | News</a></li>
            <li class="list-group-item"><a href="{% url 'research:index' %}">研究内容 | Research</li>
            <li class="list-group-item"><a href="{% url 'member:index' %}">メンバー | Member</a></li>
            <li class="list-group-item">研究室について   | Aount Lab</li>
          </ul>
        </div>
      </div>
    </div>

    <footer class='bg-dark text-white text-center py-3'>
      <p>Copyright © 2018-2019  Mori Group all right reserved.contact 住所 電話 メール 大学 学部 学科 コースへのリンク</p>
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block extrajs %}
    {% endblock %}
  </body>
</html>

homepage/member/templates/member/member_list.html
{% extends 'news/base.html' %}

{% block content %}

<!--  准教授 -->
{% for qs1 in qs1s %}
<h3> {{qs1.publish_name}} </h3>
<p> 身分    :       {{qs1.get_position_display}} </p>
<p> 出身地  :       {{qs1.birthplace}} </p>
<p> 趣味    :       {{qs1.hobby}} </p>
<hr>
{% endfor %}

<!--  助教授 -->
{% for qs2 in qs2s %}
<h3> {{qs2.publish_name}} </h3>
<p> 身分    :       {{member.get_position_display}} </p>
<p> 趣味    :       {{member.hobby | linebreaksbr | urlize}} </p>
<hr>
{% endfor %}

<!--  技術職員 -->
{% for qs3 in qs3s %}
<h3> {{qs3.publish_name}} </h3>
<p> 身分    :       {{member.get_position_display}} </p>
<p> 趣味    :       {{member.hobby| linebreaksbr | urlize}} </p>
<hr>
{% endfor %}

<!-- M2 -->
{% for qs8 in qs8s %}
<h3> {{qs8.publish_name}} </h3>
<p> 身分    :       {{member.get_position_display}} </p>
<p> 趣味    :       {{member.hobby| linebreaksbr | urlize}} </p>
<hr>
{% endfor %}

<!-- M1 -->
{% for qs9 in qs9s %}
<h3> {{qs9.publish_name}} </h3>
<p> 身分    :       {{member.get_position_display}} </p>
<p> 趣味    :       {{member.hobby| linebreaksbr | urlize}} </p>
<hr>
{% endfor %}

<!-- B4 -->
{% for qs10 in qs10s %}
<h3> {{qs10.publish_name}} </h3>
<p> 身分    :       {{member.get_position_display}} </p>
<p> 一言    :       {{member.hobby| linebreaksbr | urlize}} </p>
<hr>
{% endfor %}

{% endblock %}

homepage/news/templates/news/base.html
{% load static %}

<!doctype html>
<html lang="ja">
  <head>
    <title>mlab</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/news.css' %}">

    {% block extracss %}
    {% endblock %}

    <!-- <title>{% block title%}{% endblock %}</title> -->
  </head>
  <body class="news">
   <nav class="navbar navbar-expand-md navbar-dark bg-dark">
     <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="Navber">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'news:top' %}">Home</a>
          <li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="# ">Profile</a>
          </li> -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'news:index' %}">News</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'research:index' %}">Research</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'member:index' %}">Member</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'lab:index' %}">About Lab</a>
          </li>
          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0 ml-auto" method="GET" action="{% url 'news:index' %}">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="keyword">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>


    <div class="jumbotron">
        <h1 class="display-3">welcome mlab </h1>
        <p class="lead">X線検出器開発や天体解析をしています。</p>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}
          {% for post in post_list %}
          <div class="card mb-3">
            <a class="text-dark btn" href="{% url 'news:detail' post.pk %}">
              <div class="card-body">
                <p>
                  <img src="{{ post.image.url }}" align="left" alt="写真" width="200" height="200">
                  <h3>{{ post.title }}</h3>
                </p>
                <class="card-text">
                  <p>{{ post.text | truncatechars:20 }}</p>
                  <p><font color="#666666">{{ post.created_at }} {{ post.category }}</font></p>
                </p>
              </div>
            </a>
          </div>
          {% endfor %}
          {% endblock %}
        </div>

        <div class="col-md-4">
          <ul class="list-group">
            <h4 class="text-center">目次 | Contents</h4>
            <li class="list-group-item"><a href="{% url 'news:top' %}">ホーム   | Home</a></li>
            <li class="list-group-item"><a href="{% url 'news:index' %}">ニュース | News</a></li>
            <li class="list-group-item"><a href="{% url 'research:index' %}">研究内容 | Research</a></li>
            <li class="list-group-item"><a href="{% url 'member:index' %}">メンバー | Member</a></li>
            <li class="list-group-item"><a href="{% url 'lab:index' %}">研究室について   | Aount Lab</a></li>
          </ul>
          <br></br>
          <ul class="list-group">
            <!-- <li class="list-group-item">カテゴリー一覧</li> -->
            <h4 class="text-center">カテゴリー一覧</h4>
            {%  for category in category_list %}
            <li class="list-group-item"><a href="{% url 'news:category' category.pk %}">{{ category }}</a></li>
            {% endfor %}
          </ul>
          <br></br>
        </div>
      </div>
    </div>

    <footer class='bg-dark text-white text-center py-3'>
      <p>Copyright © 2018-2019  Mori Group all right reserved.contact 住所 電話 メール 大学 学部 学科 コースへのリンク</p>
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block extrajs %}
    {% endblock %}
  </body>
</html>

homepage/news/templates/news/post_detail.html
{% extends "news/base.html" %}
{% load static %}

{% block extracss %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock %}


{% block content %}

<div class="card mb-3">
  <!-- <img class="card-img-top" src="/images/pathToYourImage.png" alt="Card image cap"> -->
  <div class="card-body">
    <h2 class="card-header bg-dark text-white">{{ post.title }}</h2>
    <div class="card-body">
      <p>{{ post.created_at }} {{ post.category }}</p>
      <p><img src="{{ post.image.url }}" alt="写真"></p>
      {{ post.text | linebreaksbr | urlize }}
    </div>
  </div>
</div>


{% endblock %}

homepage/news/templates/news/post_list.html
{% extends 'news/base.html' %}

{% block content %}
{% for post in post_list %}
<div class="card mb-3">
  <a href="{% url 'news:detail' post.pk %}">
    <div class="card-body">
      <p>
        <img src="{{ post.image.url }}" align="left" alt="写真" width="300" height="200">
        <h3>{{ post.title }}</h3>
      </p>
      <class="card-text">
        <p>{{ post.text | linebreaksbr | truncatechars:20 }}</p>
        <p><font color="#666666">{{ post.created_at }} {{ post.category }}</font></p>
      </p>
    </div>
  </a>
</div>
{% endfor %}

{% include 'news/page.html' %}
{% endblock %}

homepage/news/templates/news/top.html
{% load static %}

<!doctype html>
<html lang="ja">
  <head class="head">

    <title>mlab</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/news.css' %}">

    {% block extracss %}
    {% endblock %}

  </head>

  <!-- ナビゲーションバーの設定 -->
  <body class="news">
   <nav class="navbar navbar-expand-md navbar-dark bg-dark">
     <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="Navber">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'news:top' %}">Home</a>
          <li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="# ">Profile</a>
          </li> -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'news:index' %}">News</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'research:index' %}">Research</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'member:index' %}">Member</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'lab:index' %}">About Lab</a>
          </li>
          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0 ml-auto" method="GET" action="{% url 'news:index' %}">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="keyword">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <!-- ジャンボトロンの設定 -->
    <div class="jumbotron">
        <h1 class="display-3">welcome mlab </h1>
        <p class="lead">X線検出器開発や天体解析をしています。</p>
    </div>

    <!-- 最新のニュースを3つ表示 -->
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}
          {% for post in post_list %}
          <div class="card mb-3">
            <a href="{% url 'news:detail' post.pk %}">
              <div class="card-body">
                <p>
                  <img src="{{ post.image.url }}" align="left" alt="写真" width="300" height="200">
                  <h3>{{ post.title }}</h3>
                </p>
                <class="card-text">
                  <p>{{ post.text | linebreaksbr | truncatechars:40 }}</p>
                  <p><font color="#666666">{{ post.created_at }} {{ post.category }}</font></p>
                </p>
              </div>
            </a>
          </div>
          {% endfor %}
          {% endblock %}
        </div>

        <!-- 目次の設定 -->
        <div class="col-md-4">
          <ul class="list-group">
            <h4 class="text-center">目次 | Contents</h4>
            <li class="list-group-item"><a href="{% url 'news:top' %}">ホーム   | Home</a></li>
            <li class="list-group-item"><a href="{% url 'news:index' %}">ニュース | News</a></li>
            <li class="list-group-item"><a href="{% url 'research:index' %}">研究内容 | Research</a></li>
            <li class="list-group-item"><a href="{% url 'member:index' %}">メンバー | Member</a></li>
            <li class="list-group-item"><a href="{% url 'lab:index' %}">研究室について   | Aount Lab</a></li>
          </ul>
          <h1></h1>
        </div>
      </div>
    </div>

    <!-- フッターの設定 -->
    <footer class='bg-dark text-white text-center py-3'>
      <p>Copyright © 2018-2019  Mori Group all right reserved.contact 住所 電話 メール 大学 学部 学科 コースへのリンク</p>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <!-- 追加するjsの設定 -->
    {% block extrajs %}
    {% endblock %}

  </body>
</html>

homepage/research/templates/research/research_list.html
{% extends 'news/base.html' %}

{% block content %}
{% for research in research_list %}
<h3>{{ research.title }}</h3>
<p>{{ research.text | linebreaksbr | urlize }}</p>
{% endfor %}
{% endblock %}